TMDL/urls.py
from django.contrib import admin
from django.urls import path
from .views import index, classic_extendedlist, classic_legacylist, classic_stat_viewer, platformer_mainlist, platformer_stat_viewer, guidelines

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('classic_extendedlist/', classic_extendedlist, name='classic_extendedlist'),
    path('classic_legacylist/', classic_legacylist, name='classic_legacylist'),
    path('classic_stat_viewer/', classic_stat_viewer, name='classic_stat_viewer'),
    path('platformer_mainlist/', platformer_mainlist, name='platformer_mainlist'),
    path('platformer_stat_viewer/', platformer_stat_viewer, name='platformer_stat_viewer'),
    path('guidelines/', guidelines, name='guidelines'),
]

classicdemonlist/models/classiclevelrecord.py
from django.db import models
from classicdemonlist.models.classicplayer import ClassicPlayer
from classicdemonlist.models.classiclevel import ClassicLevel
import math
from django.core.validators import MaxValueValidator
from django.db.models.signals import post_save
from django.dispatch import receiver

class ClassicLevelRecord(models.Model):
    player = models.ForeignKey(ClassicPlayer, on_delete=models.CASCADE)
    level = models.ForeignKey(ClassicLevel, on_delete=models.CASCADE, null=True)
    record_percentage = models.PositiveIntegerField(default=0, validators=[MaxValueValidator(100)])
    record_video_link = models.URLField(blank=True)

    class Meta:
        unique_together = ['level', 'player']

    def update_player_points(self):
        level = self.level
        player = self.player
        record_percentage = self.record_percentage

        if record_percentage == 100:
            points = level.points
        elif level.min_completion < record_percentage < 100:
            points = level.min_points

        if player.points != points:
            player.points = points
            player.save(update_fields=['points'])

    def save(self, *args, **kwargs):
        if self.pk is None:
            if not self.level.first_victor or self.record_percentage == 100:
                self.level.first_victor = self.player
                self.level.save()

        super(ClassicLevelRecord, self).save(*args, **kwargs)
        self.update_player_points()

    class Meta:
        verbose_name = "Classic Level Record"
        verbose_name_plural = "Classic Level Records"

    def __str__(self):
        return f"{self.player.name} - {self.level.name} ({self.record_percentage}%)"
    
@receiver(post_save, sender=ClassicLevelRecord)
def update_player_points_signal(sender, instance, **kwargs):
    instance.update_player_points()

normaldemonlist/models/normallevel.py
from django.db import models
import math
from django.core.validators import MaxValueValidator
from django.db.models.signals import post_save
from django.dispatch import receiver

class NormalLevel(models.Model):
    DIFFICULTIES = [
        ('Hard Demon', 'Hard Demon'),
        ('Insane Demon', 'Insane Demon'),
        ('Extreme Demon', 'Extreme Demon'),
    ]

    DURATIONS = [
        ('Tiny', 'Tiny'),
        ('Short', 'Short'),
        ('Medium', 'Medium'),
        ('Long', 'Long'),
        ('XL', 'XL'),
    ]

    levelid = models.CharField(max_length=255)
    name = models.CharField(max_length=255, blank=True)
    publisher = models.CharField(max_length=255, blank=True)
    ranking = models.PositiveIntegerField(default=0)
    difficulty = models.CharField(max_length=255, choices=DIFFICULTIES, blank=True)
    duration = models.CharField(max_length=255, choices=DURATIONS, blank=True)
    youtube_link = models.URLField(blank=True)
    youtube_thumbnail = models.URLField(blank=True)
    points = models.FloatField(default=0)
    min_points = models.FloatField(default=0)
    min_completion = models.PositiveIntegerField(default=0, validators=[MaxValueValidator(100)])
    first_victor = models.ForeignKey('normaldemonlist.NormalPlayer', on_delete=models.PROTECT, null=True, blank=True)

    def save(self, *args, **kwargs):
        if self.ranking is not None:
            self.points = round(500 * (1 - math.log(self.ranking, 151)), 2)
            self.min_points = round((500 * (1 - math.log(self.ranking, 151))) * 1/3, 2)
        else:
            self.points = None
            self.min_points = None

        super(NormalLevel, self).save(*args, **kwargs)
  
    def __str__(self):
        return f"{self.levelid} - {self.name}"
    
@receiver(post_save, sender='normaldemonlist.NormalPlayer')
@receiver(post_save, sender='normaldemonlist.NormalLevelRecord')
def update_region_points(sender, instance, **kwargs):
    from normaldemonlist.models.normalplayer import NormalPlayer
    from normaldemonlist.models.normallevelrecord import NormalLevelRecord
    
    if isinstance(instance, NormalPlayer):
        region = instance.region
    elif isinstance(instance, NormalLevelRecord):
        region = instance.player.region
    
    region.points = region.calculate_points()
    region.save()

@receiver(post_save, sender=NormalLevel)
def create_level_record(sender, instance, created, **kwargs):
    from normaldemonlist.models.normallevelrecord import NormalLevelRecord
    if created and instance.first_victor:
        player = instance.first_victor
        if instance.youtube_link:
            record_video_link = instance.youtube_link
            level_record = NormalLevelRecord.objects.create(player=player, level=instance, record_percentage=100, record_video_link=record_video_link)
        else:
            print(instance.youtube_link)
            level_record = NormalLevelRecord.objects.create(player=player, level=instance, record_percentage=100)

@receiver(post_save, sender=NormalLevel)
def update_min_completion(sender, instance, **kwargs):
    if instance.ranking > 75 and instance.min_completion != 100:
        instance.min_completion = 100
        instance.save(update_fields=['min_completion'])

platformerdemonlist/models/platformerlevelrecord.py
from django.db import models
from platformerdemonlist.models.platformerplayer import PlatformerPlayer
from platformerdemonlist.models.platformerlevel import PlatformerLevel
import math
from datetime import timedelta
from django.db.models.signals import post_save
from django.dispatch import receiver

class PlatformerLevelRecord(models.Model):
    player = models.ForeignKey(PlatformerPlayer, on_delete=models.CASCADE)
    level = models.ForeignKey(PlatformerLevel, on_delete=models.CASCADE, null=True)
    record_time = models.DurationField(default=timedelta(minutes=30))
    record_video_link = models.URLField(blank=True)

    def update_player_points(self):
        level = self.level
        player = self.player
        points = level.points

        if player.points != points:
            player.points = points
            player.save(update_fields=['points'])

    def save(self, *args, **kwargs):
        if self.pk is None:
            if not self.level.record_holder:
                self.level.record_holder = self.player
                self.level.save()

        super(PlatformerLevelRecord, self).save(*args, **kwargs)
        self.update_player_points()

    class Meta:
        verbose_name = "Platformer Level Record"
        verbose_name_plural = "Platformer Level Records"

    def __str__(self):
        return f"{self.player.name} - {self.level.name} ({self.record_time})"
    
@receiver(post_save, sender=PlatformerLevelRecord)
def update_player_points_signal(sender, instance, **kwargs):
    instance.update_player_points()

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </head>
<body class="d-flex flex-column vh-100">
    <nav class="navbar navbar-expand-lg bg-light sticky-top justify-content-center">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'index' %}"><strong>TMDL.</strong></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="{% url 'index' %}" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Classic Demonlist
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'index' %}">Main list</a></li>
                    <li><a class="dropdown-item" href="{% url 'classic_extendedlist' %}">Extended List</a></li>
                    <li><a class="dropdown-item" href="{% url 'classic_legacylist' %}">Legacy List</a></li>
                    <li><a class="dropdown-item" href="{% url 'classic_stat_viewer' %}">Stat Viewer</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Platformer Demonlist
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'platformer_mainlist' %}">Main list</a></li>
                    <li><a class="dropdown-item disabled" href="#">Extended List</a></li>
                    <li><a class="dropdown-item disabled" href="#">Legacy List</a></li>
                    <li><a class="dropdown-item" href="{% url 'platformer_stat_viewer' %}">Stat Viewer</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'guidelines' %}">Guidelines</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    {% block content %}
    {% endblock %}
    <footer class="bg-body-tertiary text-center text-lg-start mt-auto">
      <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.05);">
          Made by <strong><a class="text-body" href="https://github.com/apostorial" target="_blank">Apostorial</a></strong>
          <br>
          <strong>TMDL</strong> is not affiliated with RobTopGames
        </div>
    </footer>
</body>
</html>

templates/classic_extendedlist.html
{% extends "base.html" %}
{% load static %}
{% block title %}Classic Extended List{% endblock %}
{% block content %}
  {% for level in classic_extended_levels|dictsort:"ranking" %}
  <div class="card mt-3 mx-auto" style="width: 780px;">
    <div class="row g-0">
      <div class="col-md-4">
        <a href="{{ level.youtube_link }}" target="_blank"><img src="{{ level.youtube_thumbnail }}" class="img-fluid rounded-start" style="width: 100%;"></a>
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title text-decoration-none text-black"><a style="cursor: pointer;" data-bs-toggle="modal" data-bs-target="#modal{{level.levelid}}">#{{ level.ranking }} - {{ level.name }}</a></h5>
          <p class="card-text"><strong>Published by:</strong> {{ level.publisher }}</p>
          <button type="button" class="btn btn-primary"  data-bs-placement="right" data-bs-content="Copied to clipboard!" data-bs-toggle="popover" data-bs-container="body" data-level-id="{{ level.levelid }}" id="liveAlertBtn">Copy Level ID</button>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade" id="modal{{level.levelid}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">{{ level.name }} details</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p><strong>Level ID:</strong> {{ level.levelid }}</p>
          <p><strong>Duration:</strong> {{ level.duration }}</p>
          <p><strong>Publisher:</strong> {{ level.publisher }}</p>
          <p><strong>Difficulty:</strong> {{ level.get_difficulty_display }}</p>
          <p><strong>Ranking:</strong> {{ level.ranking }}</p>
          <p><strong>Points:</strong> {{ level.points }}</p>
          <p><strong>Min points:</strong> {{ level.min_points }}</p>
          <p><strong>List percentage:</strong> {{ level.min_completion }}%</p>
          <h2>Records for {{ level.name }}:</h2>
        </div>
        <ul>
          {% for record in level.classiclevelrecord_set.all reversed%}
            <li>{{ record.player.name }} - {{ record.record_percentage }}% - <a href="{{ record.record_video_link }}" target="_blank" style="text-decoration: none;">YouTube</a></li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
  {% endfor %} 
<script>
  document.addEventListener("DOMContentLoaded", function () {
  const popoverTriggerList = document.querySelectorAll('[data-bs-toggle="popover"]');
  const popoverList = [...popoverTriggerList].map(popoverTriggerEl => new bootstrap.Popover(popoverTriggerEl, {
    delay: { "show": 0, "hide": 2000 }
  }));
  var copyButtons = document.querySelectorAll(".btn");
    copyButtons.forEach(function (button) {
        button.addEventListener("click", function () {
          var levelId = button.getAttribute("data-level-id");
          copyToClipboardAndShowPopover(button, levelId);
      });
    });
  });

  function copyToClipboard(text) {
    var textarea = document.createElement("textarea");
    textarea.value = text;
    document.body.appendChild(textarea);
    textarea.select();
    document.execCommand("copy");
    document.body.removeChild(textarea);
  }

  function copyToClipboardAndShowPopover(element, text) {
    copyToClipboard(text);
    const popover = bootstrap.Popover.getInstance(element);
    popover.show();
    setTimeout(() => {
      popover.hide();
    }, 2000);
  }
</script>
{% endblock %}

templates/classic_legacylist.html
{% extends "base.html" %}
{% load static %}
{% block title %}Classic Legacy List{% endblock %}
{% block content %}
  {% for level in classic_legacy_levels|dictsort:"ranking" %}
  <div class="card mt-3 mx-auto" style="width: 780px;">
    <div class="row g-0">
      <div class="col-md-4">
        <a href="{{ level.youtube_link }}" target="_blank"><img src="{{ level.youtube_thumbnail }}" class="img-fluid rounded-start" style="width: 100%;"></a>
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title text-decoration-none text-black"><a style="cursor: pointer;" data-bs-toggle="modal" data-bs-target="#modal{{level.levelid}}">#{{ level.ranking }} - {{ level.name }}</a></h5>
          <p class="card-text"><strong>Published by:</strong> {{ level.publisher }}</p>
          <button type="button" class="btn btn-primary"  data-bs-placement="right" data-bs-content="Copied to clipboard!" data-bs-toggle="popover" data-bs-container="body" data-level-id="{{ level.levelid }}" id="liveAlertBtn">Copy Level ID</button>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade" id="modal{{level.levelid}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">{{ level.name }} details</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p><strong>Level ID:</strong> {{ level.levelid }}</p>
          <p><strong>Duration:</strong> {{ level.duration }}</p>
          <p><strong>Publisher:</strong> {{ level.publisher }}</p>
          <p><strong>Difficulty:</strong> {{ level.get_difficulty_display }}</p>
          <p><strong>Ranking:</strong> {{ level.ranking }}</p>
          <p><strong>Points:</strong> {{ level.points }}</p>
          <p><strong>Min points:</strong> {{ level.min_points }}</p>
          <p><strong>List percentage:</strong> {{ level.min_completion }}%</p>
          <h2>Records for {{ level.name }}:</h2>
        </div>
        <ul>
          {% for record in level.classiclevelrecord_set.all reversed%}
            <li>{{ record.player.name }} - {{ record.record_percentage }}% - <a href="{{ record.record_video_link }}" target="_blank" style="text-decoration: none;">YouTube</a></li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
  {% endfor %} 
<script>
  document.addEventListener("DOMContentLoaded", function () {
  const popoverTriggerList = document.querySelectorAll('[data-bs-toggle="popover"]');
  const popoverList = [...popoverTriggerList].map(popoverTriggerEl => new bootstrap.Popover(popoverTriggerEl, {
    delay: { "show": 0, "hide": 2000 }
  }));
  var copyButtons = document.querySelectorAll(".btn");
    copyButtons.forEach(function (button) {
        button.addEventListener("click", function () {
          var levelId = button.getAttribute("data-level-id");
          copyToClipboardAndShowPopover(button, levelId);
      });
    });
  });

  function copyToClipboard(text) {
    var textarea = document.createElement("textarea");
    textarea.value = text;
    document.body.appendChild(textarea);
    textarea.select();
    document.execCommand("copy");
    document.body.removeChild(textarea);
  }

  function copyToClipboardAndShowPopover(element, text) {
    copyToClipboard(text);
    const popover = bootstrap.Popover.getInstance(element);
    popover.show();
    setTimeout(() => {
      popover.hide();
    }, 2000);
  }
</script>
{% endblock %}

templates/classic_stat_viewer.html
{% extends "base.html" %}
{% load static %}
{% block title %}Classic Stat Viewer{% endblock %}
{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-lg-6">
            <div class="map-section">
                <div style="min-height:696px">
                    <script type="text/javascript" defer src="https://datawrapper.dwcdn.net/xCkE3/embed.js?v=9" charset="utf-8"></script>
                    <noscript><img src="https://datawrapper.dwcdn.net/xCkE3/full.png" alt="" /></noscript>
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="accordion ml-5">
                {% for region in regions|dictsortreversed:"points" %}
                    <div class="accordion-item">
                        <h2 class="accordion-header">
                            <button class="accordion-button bg-white" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne{{region.id}}" aria-expanded="false" aria-controls="panelsStayOpen-collapseOne">
                                {{region}}
                            </button>
                        </h2>
                        <div id="panelsStayOpen-collapseOne{{region.id}}" class="accordion-collapse collapse">
                            <div class="accordion-body">
                                {% for player in region.players|dictsortreversed:"points" %}
                                    <p>{{ player.name }} - {{ player.points|floatformat:"2"}} points</p>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}Classic Main List{% endblock %}
{% block content %}
  {% for level in classic_levels|dictsort:"ranking" %}
  <div class="card mt-3 mx-auto{% if forloop.last %} mb-3{% endif %}" style="width: 780px; max-width: 100%;">
    <div class="row g-0">
      <div class="col-md-4">
        <a href="{{ level.youtube_link }}" target="_blank"><img src="{{ level.youtube_thumbnail }}" class="img-fluid rounded-start" style="width: 100%;"></a>
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title text-decoration-none text-black"><a style="cursor: pointer;" data-bs-toggle="modal" data-bs-target="#modal{{level.levelid}}">#{{ level.ranking }} - {{ level.name }}</a></h5>
          <p class="card-text"><strong>Published by:</strong> {{ level.publisher }}</p>
          <button type="button" class="btn btn-primary"  data-bs-placement="right" data-bs-content="Copied to clipboard!" data-bs-toggle="popover" data-bs-container="body" data-level-id="{{ level.levelid }}" id="liveAlertBtn">Copy Level ID</button>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade" id="modal{{level.levelid}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">{{ level.name }} details</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p><strong>Level ID:</strong> {{ level.levelid }}</p>
          <p><strong>Duration:</strong> {{ level.duration }}</p>
          <p><strong>Publisher:</strong> {{ level.publisher }}</p>
          <p><strong>Difficulty:</strong> {{ level.get_difficulty_display }}</p>
          <p><strong>Ranking:</strong> {{ level.ranking }}</p>
          <p><strong>Points:</strong> {{ level.points }}</p>
          <p><strong>Min points:</strong> {{ level.min_points }}</p>
          <p><strong>List percentage:</strong> {{ level.min_completion }}%</p>
          <h2>Records for {{ level.name }}:</h2>
        </div>
        <ul>
          {% for record in level.classiclevelrecord_set.all reversed%}
            <li>{{ record.player.name }} - {{ record.record_percentage }}% - <a class="text-decoration-none" href="{{ record.record_video_link }}" target="_blank">YouTube</a></li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
  {% endfor %} 
<script>
  document.addEventListener("DOMContentLoaded", function () {
  const popoverTriggerList = document.querySelectorAll('[data-bs-toggle="popover"]');
  const popoverList = [...popoverTriggerList].map(popoverTriggerEl => new bootstrap.Popover(popoverTriggerEl, {
    delay: { "show": 0, "hide": 2000 }
  }));
  var copyButtons = document.querySelectorAll(".btn");
    copyButtons.forEach(function (button) {
        button.addEventListener("click", function () {
          var levelId = button.getAttribute("data-level-id");
          copyToClipboardAndShowPopover(button, levelId);
      });
    });
  });

  function copyToClipboard(text) {
    var textarea = document.createElement("textarea");
    textarea.value = text;
    document.body.appendChild(textarea);
    textarea.select();
    document.execCommand("copy");
    document.body.removeChild(textarea);
  }

  function copyToClipboardAndShowPopover(element, text) {
    copyToClipboard(text);
    const popover = bootstrap.Popover.getInstance(element);
    popover.show();
    setTimeout(() => {
      popover.hide();
    }, 2000);
  }
</script>
{% endblock %}

templates/platformer_mainlist.html
{% extends "base.html" %}
{% load static %}
{% block title %}Platformer Main List{% endblock %}
{% block content %}
  {% for level in platformer_levels|dictsort:"ranking" %}
  <div class="card mt-3 mx-auto{% if forloop.last %} mb-3{% endif %}" style="width: 780px; max-width: 100%;">
    <div class="row g-0">
      <div class="col-md-4">
        <a href="{{ level.youtube_link }}" target="_blank"><img src="{{ level.youtube_thumbnail }}" class="img-fluid rounded-start" style="width: 100%;"></a>
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title text-decoration-none text-black"><a style="cursor: pointer;" data-bs-toggle="modal" data-bs-target="#modal{{level.levelid}}">#{{ level.ranking }} - {{ level.name }}</a></h5>
          <p class="card-text"><strong>Published by:</strong> {{ level.publisher }}</p>
          <button type="button" class="btn btn-primary"  data-bs-placement="right" data-bs-content="Copied to clipboard!" data-bs-toggle="popover" data-bs-container="body" data-level-id="{{ level.levelid }}" id="liveAlertBtn">Copy Level ID</button>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade" id="modal{{level.levelid}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">{{ level.name }} details</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p><strong>Level ID:</strong> {{ level.levelid }}</p>
          <p><strong>Publisher:</strong> {{ level.publisher }}</p>
          <p><strong>Difficulty:</strong> {{ level.get_difficulty_display }}</p>
          <p><strong>Ranking:</strong> {{ level.ranking }}</p>
          <p><strong>Points:</strong> {{ level.points }}</p>
          <h2>Records for {{ level.name }}:</h2>
        </div>
        <ul>
          {% for record in level.platformerlevelrecord_set.all reversed%}
            <li>{{ record.player.name }} - <a class="text-decoration-none" href="{{ record.record_video_link }}" target="_blank">YouTube</a></li>
          {% endfor %}
        </ul>
      </div>
    </div>
  </div>
  {% endfor %} 
<script>
  document.addEventListener("DOMContentLoaded", function () {
  const popoverTriggerList = document.querySelectorAll('[data-bs-toggle="popover"]');
  const popoverList = [...popoverTriggerList].map(popoverTriggerEl => new bootstrap.Popover(popoverTriggerEl, {
    delay: { "show": 0, "hide": 2000 }
  }));
  var copyButtons = document.querySelectorAll(".btn");
    copyButtons.forEach(function (button) {
        button.addEventListener("click", function () {
          var levelId = button.getAttribute("data-level-id");
          copyToClipboardAndShowPopover(button, levelId);
      });
    });
  });

  function copyToClipboard(text) {
    var textarea = document.createElement("textarea");
    textarea.value = text;
    document.body.appendChild(textarea);
    textarea.select();
    document.execCommand("copy");
    document.body.removeChild(textarea);
  }

  function copyToClipboardAndShowPopover(element, text) {
    copyToClipboard(text);
    const popover = bootstrap.Popover.getInstance(element);
    popover.show();
    setTimeout(() => {
      popover.hide();
    }, 2000);
  }
</script>
{% endblock %}

templates/platformer_stat_viewer.html
{% extends "base.html" %}
{% load static %}
{% block title %}Platformer Stat Viewer{% endblock %}
{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-lg-6">
            <div class="map-section">
                <div style="min-height:696px">
                    <script type="text/javascript" defer src="https://datawrapper.dwcdn.net/xCkE3/embed.js?v=9" charset="utf-8"></script>
                    <noscript><img src="https://datawrapper.dwcdn.net/xCkE3/full.png" alt="" /></noscript>
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="accordion ml-5">
                {% for region in regions|dictsortreversed:"points" %}
                    <div class="accordion-item">
                        <h2 class="accordion-header">
                            <button class="accordion-button bg-white" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne{{region.id}}" aria-expanded="false" aria-controls="panelsStayOpen-collapseOne">
                                {{region}}
                            </button>
                        </h2>
                        <div id="panelsStayOpen-collapseOne{{region.id}}" class="accordion-collapse collapse">
                            <div class="accordion-body">
                                {% for player in region.players|dictsortreversed:"points" %}
                                    <p>{{ player.name }} - {{ player.points|floatformat:"2"}} points</p>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}